/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 Scene_hangar.glb -k -K -E --meta --shadows 
*/

import React from 'react'
import { useGraph } from '@react-three/fiber'
import { useGLTF, PerspectiveCamera, useAnimations } from '@react-three/drei'
import { SkeletonUtils } from 'three-stdlib'

export default function Model(props) {
  const group = React.useRef()
  const { scene, animations } = useGLTF('/Scene_hangar.glb')
  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene])
  const { nodes, materials } = useGraph(clone)
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group
        name="Scene"
        userData={{
          vertex_overlap: {},
          gltf_action_filter: [
            { keep: 0, action: null },
            { keep: 0, action: null },
            { keep: 0, action: null },
            { keep: 0, action: null },
            { keep: 0, action: null },
            { keep: 0, action: null },
            { keep: 0, action: { name: 'menuItem_liftoffAction', type: 'Action' } },
            { keep: 0, action: { name: 'menuItem_star_chap1Action', type: 'Action' } },
            { keep: 0, action: { name: 'menuItem_star_chap2Action', type: 'Action' } },
            { keep: 0, action: { name: 'menuItem_star_chap3Action', type: 'Action' } },
            { keep: 0, action: { name: 'menuItem_star_chap4Action', type: 'Action' } },
            { keep: 0, action: { name: 'menuItem_star_chap5Action', type: 'Action' } },
            { keep: 0, action: { name: 'menuItem_sv021Action', type: 'Action' } },
            { keep: 0, action: { name: 'menuItem_welcomeAction', type: 'Action' } },
            { keep: 0, action: null },
            { keep: 0, action: null },
            { keep: 1, action: null },
            { keep: 1, action: null },
            { keep: 0, action: { name: 'hangarDoors_OpeningAction', type: 'Action' } },
            { keep: 1, action: { name: 'landingGearAction', type: 'Action' } },
            { keep: 1, action: { name: 'propellersAction', type: 'Action' } },
            { keep: 1, action: { name: 'turret_1FIREAction', type: 'Action' } },
            { keep: 1, action: { name: 'turret_2FIREAction', type: 'Action' } },
            { keep: 1, action: { name: 'turret_3FIREAction', type: 'Action' } },
            { keep: 1, action: { name: 'turret_4FIREAction', type: 'Action' } },
            { keep: 1, action: { name: 'turretAction', type: 'Action' } },
            { keep: 1, action: { name: 'wheelSpinAction', type: 'Action' } },
            { keep: 1, action: { name: 'wingsAction', type: 'Action' } },
          ],
          gltf_action_filter_active: 18,
        }}>
        <group name="Scene_Collection" userData={{ name: 'Scene Collection' }}>
          <group name="PATHEMPTY" position={[0.012, 0, -32.77]} userData={{ name: 'PATHEMPTY' }} />
          <group name="exitHangar_path" userData={{ name: 'exitHangar_path' }} />
          <group name="COLLECTION_Environment" userData={{ name: 'COLLECTION_Environment' }}>
            <mesh name="ground" castShadow receiveShadow geometry={nodes.ground.geometry} material={materials.WHITE} scale={864.145} userData={{ name: 'ground' }} />
            <mesh name="hangar" castShadow receiveShadow geometry={nodes.hangar.geometry} material={materials.ImphenziaPixPal} scale={[-147.09, -73.197, -254.072]} userData={{ name: 'hangar' }} />
            <mesh name="hangar_floor" castShadow receiveShadow geometry={nodes.hangar_floor.geometry} material={materials.WHITE} position={[0, 0.001, 0]} scale={[-147.09, -73.197, -254.072]} userData={{ name: 'hangar_floor' }} />
            <group name="toolbox" position={[32.602, 0, -41.687]} userData={{ name: 'toolbox' }}>
              <mesh name="Cube009" castShadow receiveShadow geometry={nodes.Cube009.geometry} material={materials.toolbox_base} />
              <mesh name="Cube009_1" castShadow receiveShadow geometry={nodes.Cube009_1.geometry} material={materials.toolbox_handle} />
              <mesh name="Cube009_2" castShadow receiveShadow geometry={nodes.Cube009_2.geometry} material={nodes.Cube009_2.material} />
            </group>
            <group name="office" userData={{ name: 'office' }}>
              <mesh name="office_1" castShadow receiveShadow geometry={nodes.office_1.geometry} material={materials.BASIC_BLACKISH} />
              <mesh name="office_2" castShadow receiveShadow geometry={nodes.office_2.geometry} material={materials.WHITE} />
            </group>
            <mesh name="buildings" castShadow receiveShadow geometry={nodes.buildings.geometry} material={materials.WHITE} position={[-134.891, 0, -351.945]} scale={[49.27, 3.088, 84.826]} userData={{ name: 'buildings' }} />
            <mesh name="PressW_text" castShadow receiveShadow geometry={nodes.PressW_text.geometry} material={nodes.PressW_text.material} position={[9.013, 27.338, -188.116]} rotation={[Math.PI / 2, 0, Math.PI / 2]} scale={12.763} userData={{ name: 'PressW_text' }} />
            <group name="safetyCones" position={[16.567, 0, -54.747]} scale={[0.609, 1.407, 0.609]} userData={{ name: 'safetyCones' }}>
              <mesh name="Cone006" castShadow receiveShadow geometry={nodes.Cone006.geometry} material={materials.safteyCone} />
              <mesh name="Cone006_1" castShadow receiveShadow geometry={nodes.Cone006_1.geometry} material={materials.safetyCone_bottom} />
              <mesh name="Cone006_2" castShadow receiveShadow geometry={nodes.Cone006_2.geometry} material={materials.safetyCone_stripe} />
            </group>
            <mesh name="crates" castShadow receiveShadow geometry={nodes.crates.geometry} material={materials.WHITE} position={[-43.782, 0.665, -69.868]} rotation={[0, 0.692, 0]} userData={{ name: 'crates' }} />
            <mesh name="runway_strip_lights" castShadow receiveShadow geometry={nodes.runway_strip_lights.geometry} material={materials.strips} position={[1.012, 0.091, -32.772]} rotation={[0, 0, -Math.PI / 2]} userData={{ name: 'runway_strip_lights' }} />
          </group>
          <group name="COLLECTION_HangarLights" userData={{ name: 'COLLECTION_HangarLights' }}>
            <spotLight intensity={1087028.261} angle={Math.PI / 6} penumbra={0.5} decay={2} position={[-30.618, 43.524, -59.83]} rotation={[-Math.PI / 2, 0, 0]} userData={{ name: 'hangar_SpotLight_front_R' }} target={nodes.hangar_SpotLight_front_R.target}>
              <primitive object={nodes.hangar_SpotLight_front_R.target} position={[0, 0, -1]} />
            </spotLight>
            <spotLight intensity={1087028.261} angle={Math.PI / 6} penumbra={0.5} decay={2} position={[-0.182, 43.53, -59.826]} rotation={[-Math.PI / 2, 0, 0]} userData={{ name: 'hangar_SpotLight_front_Mid' }} target={nodes.hangar_SpotLight_front_Mid.target}>
              <primitive object={nodes.hangar_SpotLight_front_Mid.target} position={[0, 0, -1]} />
            </spotLight>
            <spotLight intensity={1087028.261} angle={Math.PI / 6} penumbra={0.5} decay={2} position={[31.247, 43.53, -59.826]} rotation={[-Math.PI / 2, 0, 0]} userData={{ name: 'hangar_SpotLight_front_L' }} target={nodes.hangar_SpotLight_front_L.target}>
              <primitive object={nodes.hangar_SpotLight_front_L.target} position={[0, 0, -1]} />
            </spotLight>
            <spotLight intensity={1087028.261} angle={Math.PI / 6} penumbra={0.5} decay={2} position={[-30.617, 43.53, 0.088]} rotation={[-Math.PI / 2, 0, 0]} userData={{ name: 'hangar_SpotLight_middle_R' }} target={nodes.hangar_SpotLight_middle_R.target}>
              <primitive object={nodes.hangar_SpotLight_middle_R.target} position={[0, 0, -1]} />
            </spotLight>
            <spotLight intensity={1087028.261} angle={Math.PI / 6} penumbra={0.5} decay={2} position={[-0.182, -0.088, 43.53]} userData={{ name: 'hangar_SpotLight_middle_Mid' }} target={nodes.hangar_SpotLight_middle_Mid.target}>
              <primitive object={nodes.hangar_SpotLight_middle_Mid.target} position={[0, 0, -1]} />
            </spotLight>
            <spotLight intensity={1087028.261} angle={Math.PI / 6} penumbra={0.5} decay={2} position={[31.247, 43.53, 0.088]} rotation={[-Math.PI / 2, 0, 0]} userData={{ name: 'hangar_SpotLight_middle_L' }} target={nodes.hangar_SpotLight_middle_L.target}>
              <primitive object={nodes.hangar_SpotLight_middle_L.target} position={[0, 0, -1]} />
            </spotLight>
            <spotLight intensity={1087028.261} angle={Math.PI / 6} penumbra={0.5} decay={2} position={[-30.617, 43.53, 60.242]} rotation={[-Math.PI / 2, 0, 0]} userData={{ name: 'hangar_SpotLight_back_R' }} target={nodes.hangar_SpotLight_back_R.target}>
              <primitive object={nodes.hangar_SpotLight_back_R.target} position={[0, 0, -1]} />
            </spotLight>
            <spotLight intensity={1087028.261} angle={Math.PI / 6} penumbra={0.5} decay={2} position={[-0.182, 43.53, 60.242]} rotation={[-Math.PI / 2, 0, 0]} userData={{ name: 'hangar_SpotLight_back_Mid' }} target={nodes.hangar_SpotLight_back_Mid.target}>
              <primitive object={nodes.hangar_SpotLight_back_Mid.target} position={[0, 0, -1]} />
            </spotLight>
            <spotLight intensity={1087028.261} angle={Math.PI / 6} penumbra={0.5} decay={2} position={[31.247, 43.53, 60.242]} rotation={[-Math.PI / 2, 0, 0]} userData={{ name: 'hangar_SpotLight_back_L' }} target={nodes.hangar_SpotLight_back_L.target}>
              <primitive object={nodes.hangar_SpotLight_back_L.target} position={[0, 0, -1]} />
            </spotLight>
            <spotLight intensity={407635.598} angle={0.27} penumbra={0.5} decay={2} position={[19.792, 8.093, -45.949]} rotation={[-0.729, -0.826, -0.581]} userData={{ name: 'MenuSpotLight_left' }} target={nodes.MenuSpotLight_left.target}>
              <primitive object={nodes.MenuSpotLight_left.target} position={[0, 0, -1]} />
            </spotLight>
            <spotLight intensity={135878.533} angle={0.408} penumbra={0.528} decay={2} position={[28.437, 0.761, -32.294]} rotation={[0.426, 0.738, -0.296]} userData={{ name: 'MidshipHighlight' }} target={nodes.MidshipHighlight.target}>
              <primitive object={nodes.MidshipHighlight.target} position={[0, 0, -1]} />
            </spotLight>
            <spotLight intensity={42638.69} angle={0.449} penumbra={0.493} decay={2} position={[17.087, 6.651, -37.628]} rotation={[-0.556, -0.397, -0.236]} userData={{ name: 'hangar_Spotlight_pushTractor' }} target={nodes.hangar_Spotlight_pushTractor.target}>
              <primitive object={nodes.hangar_Spotlight_pushTractor.target} position={[0, 0, -1]} />
            </spotLight>
            <spotLight intensity={271757.065} angle={0.27} penumbra={0.492} decay={2} position={[36.593, 8.093, -53.164]} rotation={[-1.912, 1.04, 1.961]} userData={{ name: 'MenuSpotLight_right' }} target={nodes.MenuSpotLight_right.target}>
              <primitive object={nodes.MenuSpotLight_right.target} position={[0, 0, -1]} />
            </spotLight>
          </group>
          <group name="EMPTYs" userData={{ name: 'EMPTYs' }}>
            <group name="blimpEMPTY" position={[0.012, 0, -32.77]} rotation={[Math.PI / 2, 0, 0]} scale={47.674} userData={{ name: 'blimpEMPTY' }} />
            <group name="cameraPositionEMPTY" position={[37.252, 1.829, -38.411]} rotation={[1.677, -0.22, -1.115]} userData={{ name: 'cameraPositionEMPTY' }} />
            <group name="menuPositionEMPTY" position={[27.753, 3.2, -51.426]} rotation={[0, 0.532, 0]} userData={{ name: 'menuPositionEMPTY' }} />
            <group name="blimp_FocalEMPTY" position={[8.837, 9.666, -51.914]} userData={{ name: 'blimp_FocalEMPTY' }} />
            <group name="doorsControlEMPTY" position={[26.762, 0, -154.832]} scale={9.414} userData={{ name: 'doorsControlEMPTY' }} />
            <group name="landingGear_closeupCamShotEMPTY" position={[6.327, 0.946, -42.646]} rotation={[Math.PI, 0.669, 3.077]} userData={{ name: 'landingGear_closeupCamShotEMPTY' }} />
            <group name="transitionToChapScreenEMPTY" position={[37.252, 1.829, -186.93]} userData={{ name: 'transitionToChapScreenEMPTY' }} />
            <group name="outside_pressKeyText" position={[9.013, 27.338, -188.116]} scale={12.924} userData={{ name: 'outside_pressKeyText' }} />
          </group>
          <group name="COLLECTION_HangarMenu" userData={{ name: 'COLLECTION_HangarMenu' }}>
            <group name="menuItem_star_chap5" position={[26.768, 1.951, -51.571]} rotation={[Math.PI / 2, 0, -0.506]} scale={[5.145, 6.998, 5.145]} userData={{ name: 'menuItem_star_chap5' }}>
              <mesh name="menuItem_star_chap5_1" castShadow receiveShadow geometry={nodes.menuItem_star_chap5_1.geometry} material={materials.menuItem_front} />
              <mesh name="menuItem_star_chap5_2" castShadow receiveShadow geometry={nodes.menuItem_star_chap5_2.geometry} material={materials.menuItem_side} />
              <mesh name="menuItem_star_chap5_3" castShadow receiveShadow geometry={nodes.menuItem_star_chap5_3.geometry} material={materials.menuItem_bevel} />
            </group>
            <group name="menuItem_welcome" position={[27.823, 4.61, -52.155]} rotation={[Math.PI / 2, 0, -0.506]} scale={[5.145, 6.998, 5.145]} userData={{ name: 'menuItem_welcome' }}>
              <mesh name="menuItem_welcome_1" castShadow receiveShadow geometry={nodes.menuItem_welcome_1.geometry} material={materials.menuItem_front} />
              <mesh name="menuItem_welcome_2" castShadow receiveShadow geometry={nodes.menuItem_welcome_2.geometry} material={materials.menuItem_side} />
              <mesh name="menuItem_welcome_3" castShadow receiveShadow geometry={nodes.menuItem_welcome_3.geometry} material={materials.menuItem_bevel} />
            </group>
            <group name="menuItem_sv021" position={[27.764, 3.88, -52.122]} rotation={[Math.PI / 2, 0, -0.506]} scale={[5.145, 6.998, 5.145]} userData={{ name: 'menuItem_sv021' }}>
              <mesh name="menuItem_sv021_1" castShadow receiveShadow geometry={nodes.menuItem_sv021_1.geometry} material={materials.menuItem_front} />
              <mesh name="menuItem_sv021_2" castShadow receiveShadow geometry={nodes.menuItem_sv021_2.geometry} material={materials.menuItem_side} />
              <mesh name="menuItem_sv021_3" castShadow receiveShadow geometry={nodes.menuItem_sv021_3.geometry} material={materials.menuItem_bevel} />
            </group>
            <group name="menuItem_liftoff" position={[27.869, 3.129, -52.18]} rotation={[Math.PI / 2, 0, -0.506]} scale={[5.145, 6.998, 5.145]} userData={{ name: 'menuItem_liftoff' }}>
              <mesh name="menuItem_liftoff_1" castShadow receiveShadow geometry={nodes.menuItem_liftoff_1.geometry} material={materials.menuItem_front} />
              <mesh name="menuItem_liftoff_2" castShadow receiveShadow geometry={nodes.menuItem_liftoff_2.geometry} material={materials.menuItem_side} />
              <mesh name="menuItem_liftoff_3" castShadow receiveShadow geometry={nodes.menuItem_liftoff_3.geometry} material={materials.menuItem_bevel} />
            </group>
            <group name="menuItem_star_chap1" position={[28.666, 1.951, -52.622]} rotation={[Math.PI / 2, 0, -0.506]} scale={[5.145, 6.998, 5.145]} userData={{ name: 'menuItem_star_chap1' }}>
              <mesh name="menuItem_star_chap1_1" castShadow receiveShadow geometry={nodes.menuItem_star_chap1_1.geometry} material={materials.menuItem_front} />
              <mesh name="menuItem_star_chap1_2" castShadow receiveShadow geometry={nodes.menuItem_star_chap1_2.geometry} material={materials.menuItem_side} />
              <mesh name="menuItem_star_chap1_3" castShadow receiveShadow geometry={nodes.menuItem_star_chap1_3.geometry} material={materials.menuItem_bevel} />
            </group>
            <group name="menuItem_star_chap2" position={[28.192, 1.951, -52.359]} rotation={[Math.PI / 2, 0, -0.506]} scale={[5.145, 6.998, 5.145]} userData={{ name: 'menuItem_star_chap2' }}>
              <mesh name="menuItem_star_chap2_1" castShadow receiveShadow geometry={nodes.menuItem_star_chap2_1.geometry} material={materials.menuItem_front} />
              <mesh name="menuItem_star_chap2_2" castShadow receiveShadow geometry={nodes.menuItem_star_chap2_2.geometry} material={materials.menuItem_side} />
              <mesh name="menuItem_star_chap2_3" castShadow receiveShadow geometry={nodes.menuItem_star_chap2_3.geometry} material={materials.menuItem_bevel} />
            </group>
            <group name="menuItem_star_chap3" position={[27.717, 1.951, -52.097]} rotation={[Math.PI / 2, 0, -0.506]} scale={[5.145, 6.998, 5.145]} userData={{ name: 'menuItem_star_chap3' }}>
              <mesh name="menuItem_star_chap3_1" castShadow receiveShadow geometry={nodes.menuItem_star_chap3_1.geometry} material={materials.menuItem_front} />
              <mesh name="menuItem_star_chap3_2" castShadow receiveShadow geometry={nodes.menuItem_star_chap3_2.geometry} material={materials.menuItem_side} />
              <mesh name="menuItem_star_chap3_3" castShadow receiveShadow geometry={nodes.menuItem_star_chap3_3.geometry} material={materials.menuItem_bevel} />
            </group>
            <group name="menuItem_star_chap4" position={[27.243, 1.951, -51.834]} rotation={[Math.PI / 2, 0, -0.506]} scale={[5.145, 6.998, 5.145]} userData={{ name: 'menuItem_star_chap4' }}>
              <mesh name="menuItem_star_chap4_1" castShadow receiveShadow geometry={nodes.menuItem_star_chap4_1.geometry} material={materials.menuItem_front} />
              <mesh name="menuItem_star_chap4_2" castShadow receiveShadow geometry={nodes.menuItem_star_chap4_2.geometry} material={materials.menuItem_side} />
              <mesh name="menuItem_star_chap4_3" castShadow receiveShadow geometry={nodes.menuItem_star_chap4_3.geometry} material={materials.menuItem_bevel} />
            </group>
            <group name="menuItem_chapters" position={[26.432, 1.666, -51.384]} rotation={[Math.PI / 2, 0, -0.506]} scale={[5.145, 6.998, 5.145]} userData={{ name: 'menuItem_chapters' }}>
              <mesh name="menuItem_chapters_1" castShadow receiveShadow geometry={nodes.menuItem_chapters_1.geometry} material={materials.menuItem_front} />
              <mesh name="menuItem_chapters_2" castShadow receiveShadow geometry={nodes.menuItem_chapters_2.geometry} material={materials.menuItem_side} />
              <mesh name="menuItem_chapters_3" castShadow receiveShadow geometry={nodes.menuItem_chapters_3.geometry} material={materials.menuItem_bevel} />
            </group>
          </group>
          <group name="COLLECTION_Cameras" userData={{ name: 'COLLECTION_Cameras' }}>
            <PerspectiveCamera name="landingGear_camera_1" makeDefault={false} far={1000} near={0.1} fov={22.895} position={[6.375, 1.099, -42.73]} rotation={[Math.PI, 0.669, 3.077]} userData={{ name: 'landingGear_camera' }} />
            <PerspectiveCamera name="Main_camera" makeDefault={false} far={3048} near={0.1} fov={44.096} position={[37.252, 1.829, -38.411]} rotation={[0.526, 1.068, -0.471]} userData={{ name: 'Main_camera' }} />
            <PerspectiveCamera name="outside2_camera_1" makeDefault={false} far={1000} near={0.1} fov={19.157} position={[-150.645, 2.286, -226.909]} rotation={[2.837, -1.156, 2.862]} userData={{ name: 'outside2_camera' }} />
            <PerspectiveCamera name="outside1_camera_1" makeDefault={false} far={1000} near={0.1} fov={22.895} position={[63.001, 1.829, -188.116]} rotation={[2.993, 0.575, -3.06]} userData={{ name: 'outside1_camera' }} />
            <PerspectiveCamera name="ROAMING_CAM" makeDefault={false} far={1000} near={0.1} fov={15.177} position={[200.342, 18.959, -323.989]} rotation={[3.098, 0.688, -3.114]} userData={{ name: 'ROAMING_CAM' }} />
          </group>
          <group name="COLLECTION_PushTractor" userData={{ name: 'COLLECTION_PushTractor' }}>
            <group name="pushTractor" position={[0, 0.076, 4.583]} userData={{ name: 'pushTractor' }}>
              <mesh name="tractorBody" castShadow receiveShadow geometry={nodes.tractorBody.geometry} material={materials.pushTractor_glass} />
              <mesh name="tractorBody_1" castShadow receiveShadow geometry={nodes.tractorBody_1.geometry} material={materials.pushTractor_tireBlack} />
              <mesh name="tractorBody_2" castShadow receiveShadow geometry={nodes.tractorBody_2.geometry} material={materials.WHITE} />
              <mesh name="tractorBody_3" castShadow receiveShadow geometry={nodes.tractorBody_3.geometry} material={materials.pushTractor_tireMainColor} />
              <mesh name="displayPanel_holder" castShadow receiveShadow geometry={nodes.displayPanel_holder.geometry} material={materials.WHITE} position={[20.977, 1.498, -49.48]} scale={[1, 1, 3.783]} userData={{ name: 'displayPanel_holder' }}>
                <mesh name="LevaPanel" castShadow receiveShadow geometry={nodes.LevaPanel.geometry} material={materials.WHITE} position={[0, 0.179, -0.001]} scale={[0.389, 0.391, 0.346]} userData={{ isAnimated: true, name: 'LevaPanel' }} />
              </mesh>
              <group name="pushTractor_leftWheel" userData={{ name: 'pushTractor_leftWheel' }}>
                <mesh name="Cube011" castShadow receiveShadow geometry={nodes.Cube011.geometry} material={materials.pushTractor_tireBlack} />
                <mesh name="Cube011_1" castShadow receiveShadow geometry={nodes.Cube011_1.geometry} material={materials.pushTractor_tireMainColor} />
              </group>
              <group name="pushTractor_rightWheel" userData={{ name: 'pushTractor_rightWheel' }}>
                <mesh name="Cube012" castShadow receiveShadow geometry={nodes.Cube012.geometry} material={materials.pushTractor_tireBlack} />
                <mesh name="Cube012_1" castShadow receiveShadow geometry={nodes.Cube012_1.geometry} material={materials.pushTractor_tireMainColor} />
              </group>
            </group>
          </group>
          <group name="COLLECTION_MotionGraphics" userData={{ name: 'COLLECTION_MotionGraphics' }}>
            <mesh name="Plane" castShadow receiveShadow geometry={nodes.Plane.geometry} material={nodes.Plane.material} position={[-96.795, 2.413, -181.444]} rotation={[1.571, -0.037, -1.556]} scale={[68.327, 25.897, 9.602]} userData={{ name: 'Plane' }} />
          </group>
          <group name="COLLECTION_HangarDoors" userData={{ name: 'COLLECTION_HangarDoors' }}>
            <mesh name="hangar_door_L" castShadow receiveShadow geometry={nodes.hangar_door_L.geometry} material={materials.WHITE} position={[15.47, 0, -79.29]} rotation={[-Math.PI, 0, 0]} scale={[-49.846, -61.268, -5.68]} userData={{ isAnimated: true, name: 'hangar_door_L' }} />
            <mesh name="hangar_door_R" castShadow receiveShadow geometry={nodes.hangar_door_R.geometry} material={materials.WHITE} position={[-14.916, 0, -79.29]} rotation={[-Math.PI, 0, 0]} scale={[-49.846, -61.268, -5.68]} userData={{ isAnimated: true, name: 'hangar_door_R' }} />
          </group>
          <mesh name="human_6ft_block" castShadow receiveShadow geometry={nodes.human_6ft_block.geometry} material={nodes.human_6ft_block.material} position={[-21.696, 0, -37.491]} rotation={[0, Math.PI / 2, 0]} scale={[0.875, 3.013, 0.5]} userData={{ name: 'human_6ft_block' }} />
          <mesh name="human_6ft_block001" castShadow receiveShadow geometry={nodes.human_6ft_block001.geometry} material={nodes.human_6ft_block001.material} position={[-22.271, 1.829, -35.086]} rotation={[0, 0.117, 0]} scale={[0.875, 3.013, 0.5]} userData={{ name: 'human_6ft_block.001' }} />
          <mesh name="human_6ft_block_insideCockpit" castShadow receiveShadow geometry={nodes.human_6ft_block_insideCockpit.geometry} material={nodes.human_6ft_block_insideCockpit.material} position={[-21.741, 2.494, -34.16]} rotation={[0, Math.PI / 2, 0]} scale={[0.875, 3.013, 0.5]} userData={{ name: 'human_6ft_block_insideCockpit' }} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/Scene_hangar.glb')
