/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 Scene_title.glb -k -K -E --shadows 
*/

import React from 'react'
import { useGraph } from '@react-three/fiber'
import { useGLTF, PerspectiveCamera } from '@react-three/drei'
import { SkeletonUtils } from 'three-stdlib'

export default function Model(props) {
  const { scene } = useGLTF('/Scene_title.glb')
  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene])
  const { nodes, materials } = useGraph(clone)
  return (
    <group {...props} dispose={null}>
      <group name="Scene">
        <group name="Scene_Collection">
          <group name="blimpPath" position={[-43.454, 0, -49.295]} />
          <group name="mainBlimpCONTROLLER" position={[-55.399, 27.688, -49.314]} rotation={[0, -0.167, 0]} />
          <group name="COLLECTION_Lights">
            <directionalLight intensity={2000.977} decay={2} position={[47.382, 108.131, -141.66]} rotation={[-Math.PI / 2, 0, 0]} target={nodes.mainBlimp_Spotlight.target}>
              <primitive object={nodes.mainBlimp_Spotlight.target} position={[0, 0, -1]} />
            </directionalLight>
            <spotLight intensity={605015.802} angle={Math.PI / 2} penumbra={1} decay={2} rotation={[-Math.PI / 2, 0, 0]} target={nodes.mainLight.target}>
              <primitive object={nodes.mainLight.target} position={[0, 0, -1]} />
            </spotLight>
          </group>
          <group name="COLLECTION_Clouds">
            <group name="cloud_foreground" position={[-43.321, 40.583, -94.093]} />
            <mesh name="cloud_midground" castShadow receiveShadow geometry={nodes.cloud_midground.geometry} material={materials['Clouds.001']} position={[0, 32.49, 95.438]} rotation={[-0.022, 0.272, 0.081]} />
            <mesh name="cloud_background" castShadow receiveShadow geometry={nodes.cloud_background.geometry} material={materials['Clouds.001']} position={[-207.323, 77.638, -97.142]} rotation={[-0.351, -0.068, -0.735]} scale={0.345} />
            <mesh name="clouds_wayBackground" castShadow receiveShadow geometry={nodes.clouds_wayBackground.geometry} material={materials['Clouds.001']} position={[-81.458, 0, -12.801]} />
          </group>
          <PerspectiveCamera name="SceneCamera_1" makeDefault={false} far={700} near={0.1} fov={19.157} position={[109.102, 16.724, -229.452]} rotation={[2.662, 1.001, -2.729]} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/Scene_title.glb')
